name: Echo STAGING Environment Variable

on: [push]

jobs:
  echo-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Echo STAGING environment variable
        run: echo ${{ vars.STAGING }}
      - name: Echo STAGING environment 2
        run: echo ${{ vars.ENVIRONMENT_STAGING }}
      - name: Echo STAGING environment 2
        run: echo ${{ vars.ENVIRONMENT.STAGING }}
