name: Echo STAGING Environment Variable

on: [push]

jobs:
  echo-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Echo STAGING environment variable
        run: echo ${{ vars.APP_URL }}
