name: Cypress tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run with secret
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
        env:
          Cypress_PASS_BUG: ${{ secrets.PASS_BUG }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
          if-no-files-found: ignore
          if: always

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
          if-no-files-found: ignore
