on:
  push:
env:
  STAGING: ${{ vars.ENVIRONMENT }}

jobs:
  teste:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Echo STAGING environment variable
        run: echo ${{ env.STAGING }}
